In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [37]:
raw=pd.read_csv('train.csv')

In [64]:
raw.head()

Pclass  Sex     Age  SibSp  Parch      Fare  Embarked  Cabin_B  Cabin_C  \
0       3    0  0.2750      1      0  0.014151         0        0        0   
1       1    1  0.4750      1      0  0.139136         1        0        1   
2       3    1  0.3250      0      0  0.015469         0        0        0   
3       1    1  0.4375      1      0  0.103644         0        0        1   
4       3    0  0.4375      0      0  0.015713         0        0        0   

   Cabin_D  Cabin_E  Cabin_F  Cabin_G  Cabin_T  Cabin_U  Survived  
0        0        0        0        0        0        1         0  
1        0        0        0        0        0        0         1  
2        0        0        0        0        0        1         1  
3        0        0        0        0        0        0         1  
4        0        0        0        0        0        1         0

In [39]:
raw.drop(['PassengerId','Name','Ticket'],axis=1,inplace=True)

In [40]:
raw.isnull().sum()

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [41]:
raw.Age.fillna(raw.Age.mean(),inplace=True)

In [42]:
raw.Cabin.fillna('U',inplace=True)

In [43]:
raw['Cabin']=raw.Cabin.astype(str).str[0]

In [44]:
raw.Embarked.fillna('S',inplace=True)

In [45]:
raw['Sex']=raw.Sex.apply(lambda x: 0 if x=='male' else 1)

In [47]:
cabin_dummies=pd.get_dummies(raw.Cabin,prefix='Cabin',drop_first=True)

In [48]:
cabin_dummies

Cabin_B  Cabin_C  Cabin_D  Cabin_E  Cabin_F  Cabin_G  Cabin_T  Cabin_U
0          0        0        0        0        0        0        0        1
1          0        1        0        0        0        0        0        0
2          0        0        0        0        0        0        0        1
3          0        1        0        0        0        0        0        0
4          0        0        0        0        0        0        0        1
..       ...      ...      ...      ...      ...      ...      ...      ...
886        0        0        0        0        0        0        0        1
887        1        0        0        0        0        0        0        0
888        0        0        0        0        0        0        0        1
889        0        1        0        0        0        0        0        0
890        0        0        0        0        0        0        0        1

[891 rows x 8 columns]

In [50]:
raw=pd.concat([raw,cabin_dummies],axis=1)

In [52]:
raw.drop('Cabin',axis=1,inplace=True)

In [54]:
raw['Embarked']=raw.Embarked.apply(lambda x: 0 if x=='S' else (1 if x=='C' else 2))

In [56]:
raw.Embarked.value_counts()

0    646
1    168
2     77
Name: Embarked, dtype: int64

In [58]:
raw.columns

Index(['Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked', 'Cabin_B', 'Cabin_C', 'Cabin_D', 'Cabin_E', 'Cabin_F',
       'Cabin_G', 'Cabin_T', 'Cabin_U'],
      dtype='object')

In [59]:
raw=raw[[ 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare',
       'Embarked', 'Cabin_B', 'Cabin_C', 'Cabin_D', 'Cabin_E', 'Cabin_F',
       'Cabin_G', 'Cabin_T', 'Cabin_U','Survived']]

In [61]:
raw['Age']=raw['Age'].apply(lambda x: x/raw['Age'].max())

In [63]:
raw['Fare']=raw['Fare'].apply(lambda x: x/raw['Fare'].max())

In [65]:
matrix=np.array(raw.values,'float')

In [66]:
x=matrix[:,:-1]
y=matrix[:,-1].reshape(-1,1)

In [67]:
x

array([[3.        , 0.        , 0.275     , ..., 0.        , 0.        ,
        1.        ],
       [1.        , 1.        , 0.475     , ..., 0.        , 0.        ,
        0.        ],
       [3.        , 1.        , 0.325     , ..., 0.        , 0.        ,
        1.        ],
       ...,
       [3.        , 1.        , 0.37123897, ..., 0.        , 0.        ,
        1.        ],
       [1.        , 0.        , 0.325     , ..., 0.        , 0.        ,
        0.        ],
       [3.        , 0.        , 0.4       , ..., 0.        , 0.        ,
        1.        ]])

In [68]:
y

array([[0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [0.],
       [1.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [1.],
       [1.],
       [0.],
       [1.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [1.],
       [0.],
       [0.],

In [69]:
x=np.concatenate((x,np.ones((len(x),1))),axis=1)

In [70]:
thetha0=np.zeros((x.shape[1],1))+0.5

In [71]:
thetha0

array([[0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5],
       [0.5]])

In [109]:
def sigmoid(z):
    return 1/(1+np.exp(-z))
def find_cost(h,y):
    return -1/len(x)*np.sum((y * np.log(h) + (1 - y) * np.log(1 - h)))
def gradient(h):
    return np.dot(x.T, (h - y)) / y.size
def predict_probs(X, theta):
    return sigmoid(np.dot(X, theta))
def predict(X, theta, threshold=0.5):
    return predict_probs(X, theta) >= threshold

In [112]:
def GradientDescent(thetha0 , learning_rate = 0.2 , epochs=10000 , TOL=0.00000002):
    
    thetha_history = [thetha0]
    z = np.dot(x, thetha0)
    h = sigmoid(z)
    cost_history = [find_cost(h,y)]
   
    print(f'epoch \t Cost \t')
    for epoch in range(epochs):
        print(f'{epoch:5d}\t{cost_history[-1]:7.4f}\t')
        z = np.dot(x, thetha0)
        h = sigmoid(z)
        grad = gradient(h)
        cost = find_cost(h,y)
        
        thethanew = thetha0 - learning_rate*grad
        thetha_history.append(thethanew)
        cost_history.append(cost)
        
        if np.sum((thethanew - thetha0)**2) < TOL:
            print('Convergence achieved.')
            break
        thetha0 = thethanew

    return thethanew , thetha_history , cost_history


In [113]:
thetha , thetha_history , cost_history = GradientDescent(thetha0)

epoch 	 Cost 	
    0	 1.9917	
    1	 1.9917	
    2	 1.4376	
    3	 1.0146	
    4	 0.7633	
    5	 0.6456	
    6	 0.5958	
    7	 0.5741	
    8	 0.5638	
    9	 0.5580	
   10	 0.5543	
   11	 0.5514	
   12	 0.5490	
   13	 0.5469	
   14	 0.5449	
   15	 0.5430	
   16	 0.5412	
   17	 0.5394	
   18	 0.5378	
   19	 0.5362	
   20	 0.5347	
   21	 0.5332	
   22	 0.5317	
   23	 0.5303	
   24	 0.5290	
   25	 0.5277	
   26	 0.5264	
   27	 0.5251	
   28	 0.5239	
   29	 0.5227	
   30	 0.5216	
   31	 0.5204	
   32	 0.5193	
   33	 0.5183	
   34	 0.5172	
   35	 0.5162	
   36	 0.5152	
   37	 0.5142	
   38	 0.5132	
   39	 0.5123	
   40	 0.5113	
   41	 0.5104	
   42	 0.5095	
   43	 0.5086	
   44	 0.5078	
   45	 0.5069	
   46	 0.5061	
   47	 0.5053	
   48	 0.5045	
   49	 0.5037	
   50	 0.5029	
   51	 0.5022	
   52	 0.5014	
   53	 0.5007	
   54	 0.5000	
   55	 0.4993	
   56	 0.4986	
   57	 0.4979	
   58	 0.4972	
   59	 0.4965	
   60	 0.4959	
   61	 0.4953	
   62	 0.4946	
   63	 0.4940	
   64	 0.4934	
   65	 0.4

  615	 0.4445	
  616	 0.4445	
  617	 0.4445	
  618	 0.4445	
  619	 0.4445	
  620	 0.4445	
  621	 0.4445	
  622	 0.4444	
  623	 0.4444	
  624	 0.4444	
  625	 0.4444	
  626	 0.4444	
  627	 0.4444	
  628	 0.4444	
  629	 0.4444	
  630	 0.4443	
  631	 0.4443	
  632	 0.4443	
  633	 0.4443	
  634	 0.4443	
  635	 0.4443	
  636	 0.4443	
  637	 0.4443	
  638	 0.4443	
  639	 0.4442	
  640	 0.4442	
  641	 0.4442	
  642	 0.4442	
  643	 0.4442	
  644	 0.4442	
  645	 0.4442	
  646	 0.4442	
  647	 0.4441	
  648	 0.4441	
  649	 0.4441	
  650	 0.4441	
  651	 0.4441	
  652	 0.4441	
  653	 0.4441	
  654	 0.4441	
  655	 0.4440	
  656	 0.4440	
  657	 0.4440	
  658	 0.4440	
  659	 0.4440	
  660	 0.4440	
  661	 0.4440	
  662	 0.4440	
  663	 0.4439	
  664	 0.4439	
  665	 0.4439	
  666	 0.4439	
  667	 0.4439	
  668	 0.4439	
  669	 0.4439	
  670	 0.4439	
  671	 0.4439	
  672	 0.4438	
  673	 0.4438	
  674	 0.4438	
  675	 0.4438	
  676	 0.4438	
  677	 0.4438	
  678	 0.4438	
  679	 0.4438	
  680	 0.4438	
  681	 0.4

 1265	 0.4388	
 1266	 0.4388	
 1267	 0.4388	
 1268	 0.4388	
 1269	 0.4388	
 1270	 0.4388	
 1271	 0.4388	
 1272	 0.4388	
 1273	 0.4388	
 1274	 0.4388	
 1275	 0.4388	
 1276	 0.4388	
 1277	 0.4388	
 1278	 0.4388	
 1279	 0.4388	
 1280	 0.4388	
 1281	 0.4388	
 1282	 0.4387	
 1283	 0.4387	
 1284	 0.4387	
 1285	 0.4387	
 1286	 0.4387	
 1287	 0.4387	
 1288	 0.4387	
 1289	 0.4387	
 1290	 0.4387	
 1291	 0.4387	
 1292	 0.4387	
 1293	 0.4387	
 1294	 0.4387	
 1295	 0.4387	
 1296	 0.4387	
 1297	 0.4387	
 1298	 0.4387	
 1299	 0.4386	
 1300	 0.4386	
 1301	 0.4386	
 1302	 0.4386	
 1303	 0.4386	
 1304	 0.4386	
 1305	 0.4386	
 1306	 0.4386	
 1307	 0.4386	
 1308	 0.4386	
 1309	 0.4386	
 1310	 0.4386	
 1311	 0.4386	
 1312	 0.4386	
 1313	 0.4386	
 1314	 0.4386	
 1315	 0.4386	
 1316	 0.4385	
 1317	 0.4385	
 1318	 0.4385	
 1319	 0.4385	
 1320	 0.4385	
 1321	 0.4385	
 1322	 0.4385	
 1323	 0.4385	
 1324	 0.4385	
 1325	 0.4385	
 1326	 0.4385	
 1327	 0.4385	
 1328	 0.4385	
 1329	 0.4385	
 1330	 0.4385	
 1331	 0.4

 1933	 0.4359	
 1934	 0.4359	
 1935	 0.4359	
 1936	 0.4359	
 1937	 0.4358	
 1938	 0.4358	
 1939	 0.4358	
 1940	 0.4358	
 1941	 0.4358	
 1942	 0.4358	
 1943	 0.4358	
 1944	 0.4358	
 1945	 0.4358	
 1946	 0.4358	
 1947	 0.4358	
 1948	 0.4358	
 1949	 0.4358	
 1950	 0.4358	
 1951	 0.4358	
 1952	 0.4358	
 1953	 0.4358	
 1954	 0.4358	
 1955	 0.4358	
 1956	 0.4358	
 1957	 0.4358	
 1958	 0.4358	
 1959	 0.4358	
 1960	 0.4358	
 1961	 0.4358	
 1962	 0.4358	
 1963	 0.4358	
 1964	 0.4358	
 1965	 0.4358	
 1966	 0.4358	
 1967	 0.4358	
 1968	 0.4357	
 1969	 0.4357	
 1970	 0.4357	
 1971	 0.4357	
 1972	 0.4357	
 1973	 0.4357	
 1974	 0.4357	
 1975	 0.4357	
 1976	 0.4357	
 1977	 0.4357	
 1978	 0.4357	
 1979	 0.4357	
 1980	 0.4357	
 1981	 0.4357	
 1982	 0.4357	
 1983	 0.4357	
 1984	 0.4357	
 1985	 0.4357	
 1986	 0.4357	
 1987	 0.4357	
 1988	 0.4357	
 1989	 0.4357	
 1990	 0.4357	
 1991	 0.4357	
 1992	 0.4357	
 1993	 0.4357	
 1994	 0.4357	
 1995	 0.4357	
 1996	 0.4357	
 1997	 0.4357	
 1998	 0.4357	
 1999	 0.4

 2550	 0.4343	
 2551	 0.4343	
 2552	 0.4343	
 2553	 0.4343	
 2554	 0.4343	
 2555	 0.4343	
 2556	 0.4343	
 2557	 0.4343	
 2558	 0.4343	
 2559	 0.4343	
 2560	 0.4343	
 2561	 0.4343	
 2562	 0.4343	
 2563	 0.4343	
 2564	 0.4343	
 2565	 0.4343	
 2566	 0.4343	
 2567	 0.4343	
 2568	 0.4343	
 2569	 0.4343	
 2570	 0.4343	
 2571	 0.4343	
 2572	 0.4343	
 2573	 0.4343	
 2574	 0.4343	
 2575	 0.4343	
 2576	 0.4343	
 2577	 0.4343	
 2578	 0.4343	
 2579	 0.4343	
 2580	 0.4343	
 2581	 0.4343	
 2582	 0.4343	
 2583	 0.4343	
 2584	 0.4343	
 2585	 0.4343	
 2586	 0.4343	
 2587	 0.4343	
 2588	 0.4343	
 2589	 0.4343	
 2590	 0.4343	
 2591	 0.4343	
 2592	 0.4343	
 2593	 0.4343	
 2594	 0.4343	
 2595	 0.4343	
 2596	 0.4343	
 2597	 0.4343	
 2598	 0.4343	
 2599	 0.4343	
 2600	 0.4342	
 2601	 0.4342	
 2602	 0.4342	
 2603	 0.4342	
 2604	 0.4342	
 2605	 0.4342	
 2606	 0.4342	
 2607	 0.4342	
 2608	 0.4342	
 2609	 0.4342	
 2610	 0.4342	
 2611	 0.4342	
 2612	 0.4342	
 2613	 0.4342	
 2614	 0.4342	
 2615	 0.4342	
 2616	 0.4

 3162	 0.4335	
 3163	 0.4335	
 3164	 0.4335	
 3165	 0.4335	
 3166	 0.4335	
 3167	 0.4335	
 3168	 0.4335	
 3169	 0.4335	
 3170	 0.4335	
 3171	 0.4334	
 3172	 0.4334	
 3173	 0.4334	
 3174	 0.4334	
 3175	 0.4334	
 3176	 0.4334	
 3177	 0.4334	
 3178	 0.4334	
 3179	 0.4334	
 3180	 0.4334	
 3181	 0.4334	
 3182	 0.4334	
 3183	 0.4334	
 3184	 0.4334	
 3185	 0.4334	
 3186	 0.4334	
 3187	 0.4334	
 3188	 0.4334	
 3189	 0.4334	
 3190	 0.4334	
 3191	 0.4334	
 3192	 0.4334	
 3193	 0.4334	
 3194	 0.4334	
 3195	 0.4334	
 3196	 0.4334	
 3197	 0.4334	
 3198	 0.4334	
 3199	 0.4334	
 3200	 0.4334	
 3201	 0.4334	
 3202	 0.4334	
 3203	 0.4334	
 3204	 0.4334	
 3205	 0.4334	
 3206	 0.4334	
 3207	 0.4334	
 3208	 0.4334	
 3209	 0.4334	
 3210	 0.4334	
 3211	 0.4334	
 3212	 0.4334	
 3213	 0.4334	
 3214	 0.4334	
 3215	 0.4334	
 3216	 0.4334	
 3217	 0.4334	
 3218	 0.4334	
 3219	 0.4334	
 3220	 0.4334	
 3221	 0.4334	
 3222	 0.4334	
 3223	 0.4334	
 3224	 0.4334	
 3225	 0.4334	
 3226	 0.4334	
 3227	 0.4334	
 3228	 0.4

 3977	 0.4328	
 3978	 0.4328	
 3979	 0.4328	
 3980	 0.4328	
 3981	 0.4328	
 3982	 0.4328	
 3983	 0.4328	
 3984	 0.4328	
 3985	 0.4328	
 3986	 0.4328	
 3987	 0.4328	
 3988	 0.4328	
 3989	 0.4328	
 3990	 0.4328	
 3991	 0.4328	
 3992	 0.4328	
 3993	 0.4328	
 3994	 0.4328	
 3995	 0.4328	
 3996	 0.4328	
 3997	 0.4328	
 3998	 0.4328	
 3999	 0.4328	
 4000	 0.4328	
 4001	 0.4328	
 4002	 0.4328	
 4003	 0.4328	
 4004	 0.4328	
 4005	 0.4328	
 4006	 0.4328	
 4007	 0.4328	
 4008	 0.4328	
 4009	 0.4328	
 4010	 0.4328	
 4011	 0.4328	
 4012	 0.4328	
 4013	 0.4328	
 4014	 0.4328	
 4015	 0.4328	
 4016	 0.4328	
 4017	 0.4328	
 4018	 0.4328	
 4019	 0.4328	
 4020	 0.4328	
 4021	 0.4328	
 4022	 0.4328	
 4023	 0.4328	
 4024	 0.4328	
 4025	 0.4328	
 4026	 0.4328	
 4027	 0.4328	
 4028	 0.4328	
 4029	 0.4328	
 4030	 0.4328	
 4031	 0.4328	
 4032	 0.4328	
 4033	 0.4328	
 4034	 0.4328	
 4035	 0.4328	
 4036	 0.4328	
 4037	 0.4328	
 4038	 0.4328	
 4039	 0.4328	
 4040	 0.4328	
 4041	 0.4328	
 4042	 0.4328	
 4043	 0.4

 4559	 0.4325	
 4560	 0.4325	
 4561	 0.4325	
 4562	 0.4325	
 4563	 0.4325	
 4564	 0.4325	
 4565	 0.4325	
 4566	 0.4325	
 4567	 0.4325	
 4568	 0.4325	
 4569	 0.4325	
 4570	 0.4325	
 4571	 0.4325	
 4572	 0.4325	
 4573	 0.4325	
 4574	 0.4325	
 4575	 0.4325	
 4576	 0.4325	
 4577	 0.4325	
 4578	 0.4325	
 4579	 0.4325	
 4580	 0.4325	
 4581	 0.4325	
 4582	 0.4325	
 4583	 0.4325	
 4584	 0.4325	
 4585	 0.4325	
 4586	 0.4325	
 4587	 0.4325	
 4588	 0.4325	
 4589	 0.4325	
 4590	 0.4325	
 4591	 0.4325	
 4592	 0.4325	
 4593	 0.4325	
 4594	 0.4325	
 4595	 0.4325	
 4596	 0.4325	
 4597	 0.4325	
 4598	 0.4325	
 4599	 0.4325	
 4600	 0.4325	
 4601	 0.4325	
 4602	 0.4325	
 4603	 0.4325	
 4604	 0.4325	
 4605	 0.4325	
 4606	 0.4325	
 4607	 0.4325	
 4608	 0.4325	
 4609	 0.4325	
 4610	 0.4325	
 4611	 0.4325	
 4612	 0.4325	
 4613	 0.4325	
 4614	 0.4325	
 4615	 0.4325	
 4616	 0.4325	
 4617	 0.4325	
 4618	 0.4325	
 4619	 0.4325	
 4620	 0.4325	
 4621	 0.4325	
 4622	 0.4325	
 4623	 0.4325	
 4624	 0.4325	
 4625	 0.4

 5111	 0.4324	
 5112	 0.4324	
 5113	 0.4324	
 5114	 0.4324	
 5115	 0.4324	
 5116	 0.4324	
 5117	 0.4324	
 5118	 0.4324	
 5119	 0.4324	
 5120	 0.4324	
 5121	 0.4324	
 5122	 0.4324	
 5123	 0.4323	
 5124	 0.4323	
 5125	 0.4323	
 5126	 0.4323	
 5127	 0.4323	
 5128	 0.4323	
 5129	 0.4323	
 5130	 0.4323	
 5131	 0.4323	
 5132	 0.4323	
 5133	 0.4323	
 5134	 0.4323	
 5135	 0.4323	
 5136	 0.4323	
 5137	 0.4323	
 5138	 0.4323	
 5139	 0.4323	
 5140	 0.4323	
 5141	 0.4323	
 5142	 0.4323	
 5143	 0.4323	
 5144	 0.4323	
 5145	 0.4323	
 5146	 0.4323	
 5147	 0.4323	
 5148	 0.4323	
 5149	 0.4323	
 5150	 0.4323	
 5151	 0.4323	
 5152	 0.4323	
 5153	 0.4323	
 5154	 0.4323	
 5155	 0.4323	
 5156	 0.4323	
 5157	 0.4323	
 5158	 0.4323	
 5159	 0.4323	
 5160	 0.4323	
 5161	 0.4323	
 5162	 0.4323	
 5163	 0.4323	
 5164	 0.4323	
 5165	 0.4323	
 5166	 0.4323	
 5167	 0.4323	
 5168	 0.4323	
 5169	 0.4323	
 5170	 0.4323	
 5171	 0.4323	
 5172	 0.4323	
 5173	 0.4323	
 5174	 0.4323	
 5175	 0.4323	
 5176	 0.4323	
 5177	 0.4

 5711	 0.4322	
 5712	 0.4322	
 5713	 0.4322	
 5714	 0.4322	
 5715	 0.4322	
 5716	 0.4322	
 5717	 0.4322	
 5718	 0.4322	
 5719	 0.4322	
 5720	 0.4322	
 5721	 0.4322	
 5722	 0.4322	
 5723	 0.4322	
 5724	 0.4322	
 5725	 0.4322	
 5726	 0.4322	
 5727	 0.4322	
 5728	 0.4322	
 5729	 0.4322	
 5730	 0.4322	
 5731	 0.4322	
 5732	 0.4322	
 5733	 0.4322	
 5734	 0.4322	
 5735	 0.4322	
 5736	 0.4322	
 5737	 0.4322	
 5738	 0.4322	
 5739	 0.4322	
 5740	 0.4322	
 5741	 0.4322	
 5742	 0.4322	
 5743	 0.4322	
 5744	 0.4322	
 5745	 0.4322	
 5746	 0.4322	
 5747	 0.4322	
 5748	 0.4322	
 5749	 0.4322	
 5750	 0.4322	
 5751	 0.4322	
 5752	 0.4322	
 5753	 0.4322	
 5754	 0.4322	
 5755	 0.4322	
 5756	 0.4322	
 5757	 0.4322	
 5758	 0.4322	
 5759	 0.4322	
 5760	 0.4322	
 5761	 0.4322	
 5762	 0.4322	
 5763	 0.4322	
 5764	 0.4322	
 5765	 0.4322	
 5766	 0.4322	
 5767	 0.4322	
 5768	 0.4322	
 5769	 0.4322	
 5770	 0.4322	
 5771	 0.4322	
 5772	 0.4322	
 5773	 0.4322	
 5774	 0.4322	
 5775	 0.4322	
 5776	 0.4322	
 5777	 0.4

 6341	 0.4321	
 6342	 0.4321	
 6343	 0.4321	
 6344	 0.4321	
 6345	 0.4321	
 6346	 0.4321	
 6347	 0.4321	
 6348	 0.4321	
 6349	 0.4321	
 6350	 0.4321	
 6351	 0.4321	
 6352	 0.4321	
 6353	 0.4321	
 6354	 0.4321	
 6355	 0.4321	
 6356	 0.4321	
 6357	 0.4321	
 6358	 0.4321	
 6359	 0.4321	
 6360	 0.4321	
 6361	 0.4321	
 6362	 0.4321	
 6363	 0.4321	
 6364	 0.4321	
 6365	 0.4321	
 6366	 0.4321	
 6367	 0.4321	
 6368	 0.4321	
 6369	 0.4321	
 6370	 0.4321	
 6371	 0.4321	
 6372	 0.4321	
 6373	 0.4321	
 6374	 0.4321	
 6375	 0.4321	
 6376	 0.4321	
 6377	 0.4321	
 6378	 0.4321	
 6379	 0.4321	
 6380	 0.4321	
 6381	 0.4321	
 6382	 0.4321	
 6383	 0.4321	
 6384	 0.4321	
 6385	 0.4321	
 6386	 0.4321	
 6387	 0.4321	
 6388	 0.4321	
 6389	 0.4321	
 6390	 0.4321	
 6391	 0.4321	
 6392	 0.4321	
 6393	 0.4321	
 6394	 0.4321	
 6395	 0.4321	
 6396	 0.4321	
 6397	 0.4321	
 6398	 0.4321	
 6399	 0.4321	
 6400	 0.4321	
 6401	 0.4321	
 6402	 0.4321	
 6403	 0.4321	
 6404	 0.4321	
 6405	 0.4321	
 6406	 0.4321	
 6407	 0.4

 7002	 0.4320	
 7003	 0.4320	
 7004	 0.4320	
Convergence achieved.


In [114]:
predict(x,thetha)

array([[False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [